version: "{build}"

environment:
  matrix:
    - nodejs_version: 0.12
    # lastest
    - nodejs_version: 0
    - nodejs_version: 4

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%PATH%
  # tool versions
  - node --version
  - npm --version
  # install modules
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off